export interface Doctor {
    id: string;
    name: string;
    specialty: string;
    photo: string;
    availability: string[];
    location: string;
    rating: number;
    price: number;
}

export interface Appointment {
    id: string;
    doctorId: string;
    dateTime: string;
    doctorName: string;
    doctorSpecialty: string;
    location: string;
}

export const specialties = [
    'Cardiology',
    'Dermatology',
    'Gastroenterology',
    'Neurology',
    'Pediatrics',
    'Psychiatry',
    'Orthopedics',
    'Oncology',
    'General Practice',
    'Endocrinology',
    'Ophthalmology',
    'Urology',
    'Pulmonology',
    'Nephrology',
    'Rheumatology',
    'Hematology'
];

export const doctors: Doctor[] = [
    {
        id: '1',
        name: 'Dr. Ahmed Khan',
        specialty: 'Cardiology',
        photo: 'https://randomuser.me/api/portraits/men/1.jpg',
        availability: ['Monday 9:00 AM', 'Monday 11:00 AM', 'Wednesday 2:00 PM', 'Friday 10:00 AM'],
        location: 'Medical Center, Building A, Room 302',
        rating: 4.8,
        price: 175.0,
    },
    {
        id: '2',
        name: 'Dr. Mohammad Al-Farsi',
        specialty: 'Dermatology',
        photo: 'https://randomuser.me/api/portraits/men/20.jpg',
        availability: ['Tuesday 10:00 AM', 'Thursday 1:00 PM', 'Thursday 3:00 PM', 'Friday 9:00 AM'],
        location: 'Dermatology Clinic, Suite 205',
        rating: 4.6,
        price: 150.0,
    },
    {
        id: '3',
        name: 'Dr. Faisal Rahman',
        specialty: 'Gastroenterology',
        photo: 'https://randomuser.me/api/portraits/men/21.jpg',
        availability: ['Monday 2:00 PM', 'Tuesday 11:00 AM', 'Wednesday 9:00 AM', 'Thursday 10:00 AM'],
        location: 'Medical Plaza, Floor 3, Room 312',
        rating: 4.9,
        price: 165.0,
    },
    {
        id: '4',
        name: 'Dr. Omar Malik',
        specialty: 'Neurology',
        photo: 'https://randomuser.me/api/portraits/men/4.jpg',
        availability: ['Monday 10:00 AM', 'Wednesday 1:00 PM', 'Thursday 11:00 AM', 'Friday 2:00 PM'],
        location: 'Neuroscience Center, Wing B, Room 415',
        rating: 4.7,
        price: 185.0,
    },
    {
        id: '5',
        name: 'Dr. Yusuf Abdullah',
        specialty: 'Pediatrics',
        photo: 'https://randomuser.me/api/portraits/men/5.jpg',
        availability: ['Tuesday 9:00 AM', 'Tuesday 1:00 PM', 'Thursday 9:00 AM', 'Friday 11:00 AM'],
        location: "Children's Health Center, Room 112",
        rating: 4.9,
        price: 140.0,
    },
    {
        id: '6',
        name: 'Dr. Ibrahim Hassan',
        specialty: 'Psychiatry',
        photo: 'https://randomuser.me/api/portraits/men/6.jpg',
        availability: ['Monday 1:00 PM', 'Wednesday 10:00 AM', 'Wednesday 3:00 PM', 'Friday 1:00 PM'],
        location: 'Mental Health Clinic, Suite 305',
        rating: 4.5,
        price: 200.0,
    },
    {
        id: '7',
        name: 'Dr. Tariq Siddiqui',
        specialty: 'Orthopedics',
        photo: 'https://randomuser.me/api/portraits/men/7.jpg',
        availability: ['Tuesday 2:00 PM', 'Wednesday 11:00 AM', 'Thursday 2:00 PM', 'Friday 9:00 AM'],
        location: 'Orthopedic Specialists, Floor 2, Room 210',
        rating: 4.6,
        price: 160.0,
    },
    {
        id: '8',
        name: 'Dr. Samir Patel',
        specialty: 'Oncology',
        photo: 'https://randomuser.me/api/portraits/men/8.jpg',
        availability: ['Monday 3:00 PM', 'Tuesday 9:00 AM', 'Thursday 1:00 PM', 'Friday 3:00 PM'],
        location: 'Cancer Treatment Center, Suite 405',
        rating: 4.8,
        price: 190.0,
    },
    {
        id: '9',
        name: 'Dr. Malik Habib',
        specialty: 'General Practice',
        photo: 'https://randomuser.me/api/portraits/men/9.jpg',
        availability: ['Monday 8:00 AM', 'Tuesday 8:00 AM', 'Wednesday 8:00 AM', 'Friday 8:00 AM'],
        location: 'Primary Care Clinic, Room 110',
        rating: 4.7,
        price: 125.0,
    },
    {
        id: '10',
        name: 'Dr. Kareem Nasser',
        specialty: 'Endocrinology',
        photo: 'https://randomuser.me/api/portraits/men/10.jpg',
        availability: ['Tuesday 10:00 AM', 'Thursday 11:00 AM', 'Friday 10:00 AM'],
        location: 'Diabetes & Hormone Center, Suite 255',
        rating: 4.9,
        price: 180.0,
    },
    {
        id: '11',
        name: 'Dr. Hassan Mahmoud',
        specialty: 'Ophthalmology',
        photo: 'https://randomuser.me/api/portraits/men/11.jpg',
        availability: ['Monday 9:00 AM', 'Tuesday 2:00 PM', 'Thursday 9:00 AM'],
        location: 'Vision Care Center, Floor 1, Room 115',
        rating: 4.6,
        price: 155.0,
    },
    {
        id: '12',
        name: 'Dr. Jamal Aziz',
        specialty: 'Urology',
        photo: 'https://randomuser.me/api/portraits/men/12.jpg',
        availability: ['Wednesday 10:00 AM', 'Wednesday 2:00 PM', 'Friday 1:00 PM'],
        location: 'Urology Specialists, Building C, Room 320',
        rating: 4.8,
        price: 170.0,
    },
    {
        id: '13',
        name: 'Dr. Adel Fahmy',
        specialty: 'Cardiology',
        photo: 'https://randomuser.me/api/portraits/men/13.jpg',
        availability: ['Tuesday 8:00 AM', 'Thursday 8:00 AM', 'Friday 12:00 PM'],
        location: 'Heart Center, Floor 4, Room 401',
        rating: 4.9,
        price: 185.0,
    },
    {
        id: '14',
        name: 'Dr. Zafar Qadir',
        specialty: 'Neurology',
        photo: 'https://randomuser.me/api/portraits/men/14.jpg',
        availability: ['Monday 11:00 AM', 'Wednesday 10:00 AM', 'Thursday 1:00 PM'],
        location: 'Brain & Spine Center, Wing A, Room 230',
        rating: 4.7,
        price: 190.0,
    },
    {
        id: '15',
        name: 'Dr. Nabil Al-Shahrani',
        specialty: 'Dermatology',
        photo: 'https://randomuser.me/api/portraits/men/6.jpg',
        availability: ['Tuesday 9:00 AM', 'Wednesday 1:00 PM', 'Friday 10:00 AM'],
        location: 'Skin Care Center, Suite 145',
        rating: 4.8,
        price: 160.0,
    },
    {
        id: '16',
        name: 'Dr. Rami Hakim',
        specialty: 'Orthopedics',
        photo: 'https://randomuser.me/api/portraits/men/16.jpg',
        availability: ['Monday 8:00 AM', 'Wednesday 2:00 PM', 'Thursday 10:00 AM'],
        location: 'Joint & Bone Center, Floor 3, Room 310',
        rating: 4.5,
        price: 165.0,
    },
    {
        id: '17',
        name: 'Dr. Khalid Mansour',
        specialty: 'Pulmonology',
        photo: 'https://randomuser.me/api/portraits/men/2.jpg',
        availability: ['Monday 10:00 AM', 'Wednesday 9:00 AM', 'Friday 11:00 AM'],
        location: 'Respiratory Center, Room 215',
        rating: 4.7,
        price: 175.0,
    },
    {
        id: '18',
        name: 'Dr. Amin Saleh',
        specialty: 'Nephrology',
        photo: 'https://randomuser.me/api/portraits/men/18.jpg',
        availability: ['Tuesday 11:00 AM', 'Thursday 2:00 PM', 'Friday 3:00 PM'],
        location: 'Kidney Care Center, Suite 310',
        rating: 4.8,
        price: 185.0,
    },
    {
        id: '19',
        name: 'Dr. Youssef Hamdi',
        specialty: 'Rheumatology',
        photo: 'https://randomuser.me/api/portraits/men/19.jpg',
        availability: ['Monday 1:00 PM', 'Wednesday 10:00 AM', 'Thursday 1:00 PM'],
        location: 'Arthritis Center, Floor 2, Room 208',
        rating: 4.6,
        price: 170.0,
    },
    {
        id: '20',
        name: 'Dr. Waleed Akbar',
        specialty: 'Hematology',
        photo: 'https://randomuser.me/api/portraits/men/20.jpg',
        availability: ['Tuesday 9:00 AM', 'Wednesday 3:00 PM', 'Friday 10:00 AM'],
        location: 'Blood Disorders Center, Room 410',
        rating: 4.9,
        price: 195.0,
    },
    {
        id: '21',
        name: 'Dr. Mustafa Karim',
        specialty: 'Cardiology',
        photo: 'https://randomuser.me/api/portraits/men/21.jpg',
        availability: ['Monday 8:00 AM', 'Tuesday 2:00 PM', 'Thursday 9:00 AM'],
        location: 'Cardiac Care Unit, Floor 3, Room 305',
        rating: 4.8,
        price: 180.0,
    },
    {
        id: '22',
        name: 'Dr. Hamza Farooq',
        specialty: 'Neurology',
        photo: 'https://randomuser.me/api/portraits/men/22.jpg',
        availability: ['Tuesday 10:00 AM', 'Wednesday 1:00 PM', 'Friday 2:00 PM'],
        location: 'Neurological Institute, Room 420',
        rating: 4.7,
        price: 190.0,
    },
    {
        id: '23',
        name: 'Dr. Bilal Abbas',
        specialty: 'Orthopedics',
        photo: 'https://randomuser.me/api/portraits/men/23.jpg',
        availability: ['Monday 9:00 AM', 'Wednesday 11:00 AM', 'Thursday 3:00 PM'],
        location: 'Sports Medicine Center, Suite 220',
        rating: 4.6,
        price: 165.0,
    },
    {
        id: '24',
        name: 'Dr. Taha Mohammed',
        specialty: 'Pediatrics',
        photo: 'https://randomuser.me/api/portraits/men/24.jpg',
        availability: ['Tuesday 8:00 AM', 'Thursday 10:00 AM', 'Friday 9:00 AM'],
        location: 'Pediatric Center, Room 105',
        rating: 4.9,
        price: 145.0,
    },
    {
        id: '25',
        name: 'Dr. Ziad Khalifa',
        specialty: 'Oncology',
        photo: 'https://randomuser.me/api/portraits/men/25.jpg',
        availability: ['Monday 11:00 AM', 'Wednesday 9:00 AM', 'Friday 1:00 PM'],
        location: 'Oncology Institute, Floor 4, Room 415',
        rating: 4.8,
        price: 200.0,
    },
    {
        id: '26',
        name: 'Dr. Raed Omar',
        specialty: 'Gastroenterology',
        photo: 'https://randomuser.me/api/portraits/men/26.jpg',
        availability: ['Tuesday 1:00 PM', 'Wednesday 10:00 AM', 'Thursday 2:00 PM'],
        location: 'Digestive Health Center, Suite 315',
        rating: 4.7,
        price: 175.0,
    },
    {
        id: '27',
        name: 'Dr. Sami Rashid',
        specialty: 'Psychiatry',
        photo: 'https://randomuser.me/api/portraits/men/27.jpg',
        availability: ['Monday 10:00 AM', 'Tuesday 3:00 PM', 'Thursday 11:00 AM'],
        location: 'Mental Wellness Center, Room 325',
        rating: 4.6,
        price: 195.0,
    },
    {
        id: '28',
        name: 'Dr. Adnan Jamil',
        specialty: 'Endocrinology',
        photo: 'https://randomuser.me/api/portraits/men/28.jpg',
        availability: ['Tuesday 9:00 AM', 'Wednesday 2:00 PM', 'Friday 10:00 AM'],
        location: 'Endocrine Center, Floor 2, Room 210',
        rating: 4.8,
        price: 185.0,
    },
    {
        id: '29',
        name: 'Dr. Faris Nasr',
        specialty: 'Urology',
        photo: 'https://randomuser.me/api/portraits/men/29.jpg',
        availability: ['Monday 2:00 PM', 'Wednesday 9:00 AM', 'Friday 11:00 AM'],
        location: 'Urology Center, Suite 320',
        rating: 4.7,
        price: 180.0,
    },
    {
        id: '30',
        name: 'Dr. Hisham Zaki',
        specialty: 'Ophthalmology',
        photo: 'https://randomuser.me/api/portraits/men/30.jpg',
        availability: ['Tuesday 10:00 AM', 'Thursday 1:00 PM', 'Friday 2:00 PM'],
        location: 'Eye Care Center, Room 125',
        rating: 4.8,
        price: 160.0,
    },
    {
        id: '31',
        name: 'Dr. Majid Salem',
        specialty: 'Dermatology',
        photo: 'https://randomuser.me/api/portraits/men/31.jpg',
        availability: ['Monday 9:00 AM', 'Wednesday 11:00 AM', 'Thursday 3:00 PM'],
        location: 'Dermatology Associates, Suite 230',
        rating: 4.7,
        price: 155.0,
    },
    {
        id: '32',
        name: 'Dr. Nader Kamal',
        specialty: 'General Practice',
        photo: 'https://randomuser.me/api/portraits/men/32.jpg',
        availability: ['Tuesday 8:00 AM', 'Wednesday 10:00 AM', 'Friday 9:00 AM'],
        location: 'Family Medicine Center, Room 115',
        rating: 4.6,
        price: 130.0,
    },
    {
        id: '33',
        name: 'Dr. Osama Darwish',
        specialty: 'Cardiology',
        photo: 'https://randomuser.me/api/portraits/men/33.jpg',
        availability: ['Monday 11:00 AM', 'Tuesday 2:00 PM', 'Thursday 10:00 AM'],
        location: 'Heart Institute, Floor 3, Room 310',
        rating: 4.9,
        price: 190.0,
    },
    {
        id: '34',
        name: 'Dr. Rayyan Abbas',
        specialty: 'Neurology',
        photo: 'https://randomuser.me/api/portraits/men/34.jpg',
        availability: ['Tuesday 9:00 AM', 'Wednesday 1:00 PM', 'Friday 11:00 AM'],
        location: 'Neurology Center, Room 425',
        rating: 4.7,
        price: 195.0,
    },
    {
        id: '35',
        name: 'Dr. Saifuddin Khan',
        specialty: 'Orthopedics',
        photo: 'https://randomuser.me/api/portraits/men/35.jpg',
        availability: ['Monday 10:00 AM', 'Thursday 2:00 PM', 'Friday 3:00 PM'],
        location: 'Orthopedic Center, Suite 240',
        rating: 4.6,
        price: 170.0,
    },
    {
        id: '36',
        name: 'Dr. Talal Ibrahim',
        specialty: 'Pediatrics',
        photo: 'https://randomuser.me/api/portraits/men/36.jpg',
        availability: ['Tuesday 8:00 AM', 'Wednesday 10:00 AM', 'Friday 9:00 AM'],
        location: "Children's Specialty Center, Room 118",
        rating: 4.8,
        price: 150.0,
    },
    {
        id: '37',
        name: 'Dr. Usman Farid',
        specialty: 'Oncology',
        photo: 'https://randomuser.me/api/portraits/men/37.jpg',
        availability: ['Monday 1:00 PM', 'Wednesday 9:00 AM', 'Thursday 11:00 AM'],
        location: 'Cancer Care Center, Floor 4, Room 420',
        rating: 4.9,
        price: 205.0,
    },
    {
        id: '38',
        name: 'Dr. Waseem Akhtar',
        specialty: 'Gastroenterology',
        photo: 'https://randomuser.me/api/portraits/men/38.jpg',
        availability: ['Tuesday 10:00 AM', 'Thursday 2:00 PM', 'Friday 1:00 PM'],
        location: 'GI Health Center, Suite 325',
        rating: 4.7,
        price: 180.0,
    },
    {
        id: '39',
        name: 'Dr. Yasir Qureshi',
        specialty: 'Psychiatry',
        photo: 'https://randomuser.me/api/portraits/men/39.jpg',
        availability: ['Monday 9:00 AM', 'Wednesday 11:00 AM', 'Friday 10:00 AM'],
        location: 'Behavioral Health Center, Room 335',
        rating: 4.6,
        price: 190.0,
    },
    {
        id: '40',
        name: 'Dr. Zubair Malik',
        specialty: 'Endocrinology',
        photo: 'https://randomuser.me/api/portraits/men/40.jpg',
        availability: ['Tuesday 8:00 AM', 'Thursday 10:00 AM', 'Friday 9:00 AM'],
        location: 'Endocrine Specialists, Floor 2, Room 215',
        rating: 4.8,
        price: 185.0,
    },
    {
        id: '41',
        name: 'Dr. Akram Hassan',
        specialty: 'Urology',
        photo: 'https://randomuser.me/api/portraits/men/41.jpg',
        availability: ['Monday 10:00 AM', 'Wednesday 2:00 PM', 'Friday 11:00 AM'],
        location: 'Urology Associates, Suite 330',
        rating: 4.7,
        price: 175.0,
    },
    {
        id: '42',
        name: 'Dr. Basil Ahmed',
        specialty: 'Ophthalmology',
        photo: 'https://randomuser.me/api/portraits/men/42.jpg',
        availability: ['Tuesday 9:00 AM', 'Thursday 1:00 PM', 'Friday 2:00 PM'],
        location: 'Vision Specialists, Room 130',
        rating: 4.8,
        price: 165.0,
    },
    {
        id: '43',
        name: 'Dr. Fahad Raza',
        specialty: 'Dermatology',
        photo: 'https://randomuser.me/api/portraits/men/43.jpg',
        availability: ['Monday 8:00 AM', 'Wednesday 10:00 AM', 'Thursday 3:00 PM'],
        location: 'Skin Health Center, Suite 235',
        rating: 4.7,
        price: 160.0,
    },
    {
        id: '44',
        name: 'Dr. Ghassan Mahmood',
        specialty: 'General Practice',
        photo: 'https://randomuser.me/api/portraits/men/44.jpg',
        availability: ['Tuesday 8:00 AM', 'Wednesday 9:00 AM', 'Friday 10:00 AM'],
        location: 'Primary Health Center, Room 120',
        rating: 4.6,
        price: 135.0,
    },
    {
        id: '45',
        name: 'Dr. Imran Siddique',
        specialty: 'Cardiology',
        photo: 'https://randomuser.me/api/portraits/men/45.jpg',
        availability: ['Monday 11:00 AM', 'Tuesday 2:00 PM', 'Thursday 10:00 AM'],
        location: 'Cardiac Specialists, Floor 3, Room 315',
        rating: 4.9,
        price: 195.0,
    },
    {
        id: '46',
        name: 'Dr. Junaid Akbar',
        specialty: 'Neurology',
        photo: 'https://randomuser.me/api/portraits/men/46.jpg',
        availability: ['Tuesday 9:00 AM', 'Wednesday 1:00 PM', 'Friday 11:00 AM'],
        location: 'Neuro Care Center, Room 430',
        rating: 4.8,
        price: 200.0,
    },
    {
        id: '47',
        name: 'Dr. Kamran Aziz',
        specialty: 'Orthopedics',
        photo: 'https://randomuser.me/api/portraits/men/47.jpg',
        availability: ['Monday 10:00 AM', 'Thursday 2:00 PM', 'Friday 3:00 PM'],
        location: 'Bone & Joint Center, Suite 245',
        rating: 4.7,
        price: 175.0,
    },
    {
        id: '48',
        name: 'Dr. Luqman Farooqi',
        specialty: 'Pediatrics',
        photo: 'https://randomuser.me/api/portraits/men/48.jpg',
        availability: ['Tuesday 8:00 AM', 'Wednesday 10:00 AM', 'Friday 9:00 AM'],
        location: 'Pediatric Associates, Room 122',
        rating: 4.8,
        price: 155.0,
    },
    {
        id: '49',
        name: 'Dr. Moinuddin Khan',
        specialty: 'Oncology',
        photo: 'https://randomuser.me/api/portraits/men/49.jpg',
        availability: ['Monday 1:00 PM', 'Wednesday 9:00 AM', 'Thursday 11:00 AM'],
        location: 'Oncology Specialists, Floor 4, Room 425',
        rating: 4.9,
        price: 210.0,
    },
    {
        id: '50',
        name: 'Dr. Naeem Sheikh',
        specialty: 'Gastroenterology',
        photo: 'https://randomuser.me/api/portraits/men/50.jpg',
        availability: ['Tuesday 10:00 AM', 'Thursday 2:00 PM', 'Friday 1:00 PM'],
        location: 'Digestive Care Center, Suite 330',
        rating: 4.7,
        price: 185.0,
    }
];